[project]
name = "check-nextcloud-security"
version = "0.1.0"
description = "Check the security level of your Nextcloud instance with the Nextcloud Security API "
authors = [{ name = "Massoud Ahmed", email = "trapez.klinge-4m@icloud.com" }]
requires-python = "~=3.11.0"
readme = "README.md"
dependencies = [
    "certifi>=2025.7.14,<2026",
    "requests>=2.32.4,<3",
]

[tool.uv]
package = false

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[dependency-groups]
dev = [
    "pylint>=4.0.2",
]
test = [
    "pytest>=9.0.0",
    "pytest-mock>=3.15.1",
]

[tool.pytest.ini_options]
pythonpath = "."
